name: CI

on: push

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn
      - run: yarn build:web
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - run: yarn test
        env:
          CI: true
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
      - uses: actions/upload-artifact@v1
        with:
          name: hemoguide-app.zip
          path: dist/hemoguide-app-*.*.*-mac.zip
      - uses: actions/upload-artifact@v1
        with:
          name: dist/hemoguide-app Setup.exe
          path: dist/hemoguide-app Setup *.*.*.exe
      - uses: actions/upload-artifact@v1
        with:
          name: hemoguide-app.AppImage
          path: dist/hemoguide-app-*.*.*.AppImage
